## Python numpy

In [2]:
'''
Lo primero es comprobar que tenemos instalado nmumpy y que lo podemos importar correctamente.
La ejecución de este bloque de código nos debe mostrar el array [1,2,3,4,5]
'''
import numpy as np

# Definición de un nuevo 'ndarray', de ahora en adelante lo llamaremos simplemente 'array'
test = np.array([1, 2, 3, 4, 5])
print(test)

[1 2 3 4 5]


## Primeros pasos

un tip molón para JN: #esc b / esc a para añadir celdas de código debajo o encima de la actual

### Matrices

| función |   |
|---|---|
| a = np.array() | crear un array |
| a = np.arange() | crear un array con un rango |
| a.dtype | tipo de dato almacenado |
| a.ndim | cuántas dimensiones tiene |  
| a.shape | longitud de cada dimensión |
| a.size / a.itemsize | nº elementos y tamaño |

#### np.array() y np.arange()

In [ ]:
''' 
Llamamos a np.array() para iniciar un array en numpy
'''
# de una dimensión
a = np.array([1,2,3,4,5])
print("de una dimensión:\n", a, "\n")

# de dos
b =[[1,2,3],[4,5,6]]
print("de dos dimensiones:\n", b, "\n")

# o más
c = np.array([
    [
        [1,2,3],[4,5,6]
    ],
    [
        [1,2,3],[4,5,6]
    ]   
    ])
print("o más:\n", c, "\n")

In [ ]:
''' 
Otra forma de inicializar un np.array(range()), o equivalentemente con np.arange()
np.arange() admite los mismos argumentos que range. 
'''
a = np.arange(10, 20, 2)
print(a)

#### .dtype

**dtype** nos indica el tipo de dato almacenado en una matriz. (a.dtype)

Se utiliza también como argumento de distintas funcionas, para definir el tipo cuando inicializamos una matriz (dtype = ... )

Podemos usarlo para ajustar el tipo de datos almacenandos y optimizar memoria: 
- El tipo int16 puede representar un número entero de 16 bits (2 bytes)(-32.768 a 32.767)
- El tipo int32 puede representar un número entero de 32 bits (4 bytes)(-2.147.483.648 a 2.147.483.647)
- El tipo int64 puede representar un número entero de 64 bits (8 bytes)(-9.223.372.036.854.775.808 a 92.23.372.036.854.775.807)
- El tipo float32 puede representar un número real de 32 bits (4 bytes)(-3.4028235e+38 a 3.4028235e+38)
- El tipo float64 puede representar un número real de 64 bits (8 bytes)(-1.7976931348623157e+308 a 1.7976931348623157e+308)

In [ ]:
print("por defecto, una matriz almacena datos de tipo", a.dtype)
a32 = np.array(a*10000, dtype = np.int32)
print("podemos definir a32:", a32, "con datos de tipo", a32.dtype, "\n")

'''
podemos redefinir el tipo de dato de una matriz con astype. 
astype no modifica la función original (hay que guardarlo en otra variable). 
Pero ojo, si metemos algo que se salga en memoria va a dar error -> overflow.
'''
a16 = a32.astype(np.int16)
a16 = np.array([1,2,32770], dtype=np.int16) 

print(a16, "parece que se ha roto")

#### Obtener información de una matriz

In [14]:
'''
Para obtener la información de una matriz, usamos: 
- ndim para obtener las dimensiones de un array
- shape para obtener su tamaño (shape devuelve una tupla).
- size para saber cuántos datos almacena. 
- itemsize para saber cuánto ocupa en memoria cada dato. 

'''
print("la matriz tiene", c.ndim, "dimensiones")
print("cada dimensión mide", c.shape)
print("guarda", c.size, "datos")
print("ocupa", c.itemsize, "bytes por dato")
print("en total: ", c.itemsize*c.size, "bytes")

la matriz tiene 3 dimensiones
cada dimensión mide (2, 2, 3)
guarda 12 datos
ocupa 8 bytes por dato
en total:  96 bytes


In [187]:
print("elementos de a16:", a16.size)
print("tamaño de cada elemento:", a16.itemsize)
print ("tamaño total:", a16.itemsize * a16.size)

elementos de a16: 5
tamaño de cada elemento: 2
tamaño total: 10


### Ejercicios

In [69]:
'''
Define el array 'a' del 1 al 10. 
'''
a = np.array(range(1,11)) 
print(a)

'''
Es equivalente a np.arange(10). 
La función np.arange() admite los mismos argumentos que range
'''

a = np.arange(10,0,-1)
print(a)

'''
Imprime la dimension del array y el shape
'''
print(a.ndim, a.shape)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]
1 (10,)


In [70]:
''' 
Define de un array 'b' de dimensiones 3x5 a partir de listas anidadas
'''

b = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
    ]
)

In [190]:
'''
Define un array 'c'  de dim 2x2x3 a partir de una lista de listas anidadas 
'''

c = np.array([
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
    ])
'''
Imprime el número total de elementos del array y el shape
'''
print(c.size)
print(c.shape)

12
(2, 2, 3)


## Acceder y modificar elementos de un array

Podemos acceder a los elementos de un array mediante corchetes, con índices separados por comas.
- Cada índice hace referencia a la posición del elemento en una dimensión. 
- ":" selecciona todo.  
- Cada dimensión admite 3 argumentos -> inicio, final, salto (step). 
- Se puede redefinir un elemento de una matriz igualándolo al nuevo valor. 

### Accediendo

In [25]:
# Obtener un elemento concreto de un array [r,c] row column
print(b)
print(b[1,4])
print(b[:,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
10
[ 3  8 13]


In [8]:
# Para obtener una fila completa utilizamos la notación ':' como en la listas
print(b[0,:])

# Para obtener una columna, pondremos ":" en el primer argumento
print(b[:,0])

[1 2 3 4 5]
[ 1  6 11]


In [13]:
# Para acceder de una forma un poco más avanzada se utiliza [inicio: final: paso]
print(b[1, 4:1:-1],"\n")

# acceder a las filas pares: 
print(b[::2, :], "\n")

#darle la vuelta a las filas
b_inverted=b[::-1,::-1]
print(b_inverted)

[10  9  8] 

[[ 1  2  3  4  5]
 [11 12 13 14 15]] 

[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


### Modificando

In [17]:
# Podemos actualizar la información de un array igual que seleccionando un elemento e igulandolo con un nuevo valor
print(b, "\n")

# establecer el elemento 50 a 500
b[0,4] = 500
print(b)

[[  1   2   3   4   5]
 [  6 500   8   9  10]
 [ 11  12  13  14  15]]
[[  1   2   3   4 500]
 [  6 500   8   9  10]
 [ 11  12  13  14  15]]


In [74]:
# Podemos actulizar una fila completa
print(b)
print()

# Establecer la fila 1 de b a 0
b[1,:] = 0
print(b)
print()

# Establecer la fila 1 de b 1 a 6,7,8,9,10
b[1,:] = range(6,11)
print(b)

[[ 1  2  3  4  5]
 [ 0  0  0  0  0]
 [11 12 13 14 15]]

[[ 1  2  3  4  5]
 [ 0  0  0  0  0]
 [11 12 13 14 15]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### Ejercicios

In [76]:
'''
Define un array de tamaño 10 y selecciona el valor de la posición 5
'''
a = np.arange(10)
print("la matriz", a, "tiene una longitud", a.shape, "y el quinto elemento es:",  a[4])

la matriz [0 1 2 3 4 5 6 7 8 9] tiene una longitud (10,) y el quinto elemento es: 4


In [84]:
# cambiar los elementos de la primera fila de la segunda matriz, a 0
print(c, "\n\n")

c[1,0,:]=0
print(c, "\n\n")

#cambiar la última columna de todo a 0.
# tip: podemos usar índices negativos para indicar última fila/columna/matriz... 
c[:,:,-1]=0
print(c, "\n\n")


[[[1 2 0]
  [4 5 0]]

 [[0 0 0]
  [4 5 0]]] 


[[[1 2 0]
  [4 5 0]]

 [[0 0 0]
  [4 5 0]]] 


[[[1 2 0]
  [4 5 0]]

 [[0 0 0]
  [4 5 0]]] 




In [85]:
'''
Define el array de tamaño 25 y selecciona los valores pares
'''
a = np.arange(25)
a[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [86]:
'''
Ahora selecciona los valores impares
'''
a[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [87]:
'''
Selecciona el uĺltimo valor
'''
a[-1]

24

In [90]:
"""
Invierte el orden de los valores
"""
a[::-1]

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5,  4,  3,  2,  1,  0])

In [92]:
'''
Define un array multidimensional de tamaño 2x2 y selecciona el valor de la segunda fila y la segunda columna
'''
b[1][1]

5

In [97]:
'''
Dado el array:
[
[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
]
- selecciona el valor de la segunda dimension, primera fila, segunda columna
'''
c = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(c, "\nand", c[1,0,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 
and 6


In [108]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a 99
'''
c = np.array([
    [range(3), range(3,6), range(6,9), range(9,12)],
    [range(12,15), range(15,18), range(18,21), range(21,24)],
    [range(24,27), range(27,30), range(30,33), range(33,36)], 
    [range(36,39), range(39,42), range(42,45), range(45,48)],
])
#print(c, "\n\n")

c[:,:,1] = 99
print(c)

[[[ 0 99  2]
  [ 3 99  5]
  [ 6 99  8]
  [ 9 99 11]]

 [[12 99 14]
  [15 99 17]
  [18 99 20]
  [21 99 23]]

 [[24 99 26]
  [27 99 29]
  [30 99 32]
  [33 99 35]]

 [[36 99 38]
  [39 99 41]
  [42 99 44]
  [45 99 47]]]


In [113]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a (0,1), (2,3), (4,5), (6,7)
'''
c[:,:,1]=[range(1,12,3), range(13,24,3), range(25,36,3), range(37,48,3)]
print(c)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]


## Diferentes tipos de arrays

### Matrices de valores concretos
|función| |
|---|---|
| np.zeros (shape, ...) | matriz de ceros |
| np.ones (shape, ...) | matriz de unos |
| np.full(shape, value,...) | matriz de value |
| np..._like(array) | matriz semejante (en tamaño y tipo de dato) a otra
|np.eye(size) / np.identity(size) | matriz identidad de tamaño size|

In [ ]:
'''
np.zeros -> define una matriz de ceros
- primer arg -> shape (se introduce el shape con una tupla). 
- argumento optional -> se puede indicar el tipo de dato con dtype
'''
print("matriz np.zeros(shape, dtype)\n", np.zeros((2,3,5), dtype=np.int32), "\n")
print("matriz np.zeros(b.shape)\n", np.zeros(b.shape), "\n")

'''
np.zeros_like(matriz) -> toma la forma y el tipo de dato de otra matriz
#''' 
print("matriz np.zeros_like(b)\n", np.zeros_like(b), "\n")

In [ ]:
# Dada una matriz, como b:
print("la matriz", b, "es de tipo", b.dtype)

# Podemos definir una matriz de 0:
# - con el mismo shape
zeros1 = np.zeros(b.shape)
print(zeros1)

# - con el mismo dtype: 
print(zeros1.dtype)

# - o con las mismas propiedades, en general. 
# Para esto usaremos la función 'np.zeros_like' (mismo shape y dtype)
print(np.zeros_like(l))

In [115]:
'''
np.ones es equivalente, pero crea una matriz de unos
'''
print(np.ones((2,3,5), dtype=np.int16))


[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [40]:
'''
np.full(shape, value) -> crea una matriz con value 
- también acepta como argumento dtype
- podemos usar un valor acabado en . para que np sepa que queremos un float. 
'''
p = np.full((5,3), 50.)
print(p)

'''
también podemos usar como referencia de shape y dtype otra matriz
'''
q = np.full_like(p, 75)
print(q)

[[50. 50. 50.]
 [50. 50. 50.]
 [50. 50. 50.]
 [50. 50. 50.]
 [50. 50. 50.]]


In [44]:
''' 
np.eye(size) o bien np.identity(size) -> crea una matriz identidad del tamaño indicado. 
- admite dtype como argumento
''' 
print(np.eye(5, dtype=np.int16))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


### Matriz de números aleatorios
|función| |
|---|---|
|np.random.rand(rows, columns) | valores aleatorios entre 0,1 |
|np.random.randint(min,max, shape, ...) | enteros aleatorios entre min y max|

In [118]:
'''
np.random.rand(filas, columnas) -> crear una matriz de números aleatorios entre 0 y 1. 
OJO -> en este caso no se pasa el shape dentro de una tupla, sino que es un array de dos dimensiones y su tamaño se pasa en dos parámetros
'''
np.random.rand(5,2)

# Definir una matriz de 5x3 con valores alazares mayores que 1
np.random.rand(5,3)*100

array([[0.27216292, 0.1988215 ],
       [0.61088554, 0.03954867],
       [0.561632  , 0.95394482],
       [0.08861559, 0.59442662],
       [0.68516551, 0.12322326]])

In [43]:
'''
np.random.randint -> crea una matriz de enteros aleatorios entre dos valores. 
- argumentos 1 y 2: min y max de los enteros.  
- argumento 3: shape de la matriz (en forma de tupla, ahora sí).
'''
np.random.randint(0,100, (3,4))

array([[36, 95, 90, 47],
       [88, 82, 78, 52],
       [39, 11, 92, 75]])

### Reshape

In [6]:
'''
con .reshape podemos darle una nueva forma a una matriz (de 3,2 a 1,6 o lo que sea)
'''
a = np.array(range(6))
print("la matriz a es de 1 dimensión: \n", a)
b = a.reshape(3,2)
print("le podemos dar otra forma como: \n", b)


la matriz a es de 1 dimensión: [0 1 2 3 4 5]
le podemos dar otra forma como: 
 [[0 1]
 [2 3]
 [4 5]]


### Ejercicios

In [4]:
'''
Define el array z de dim 1 completo de ceros
'''
z=np.zeros((10), np.int16)
print(z)

[0 0 0 0 0 0 0 0 0 0]


In [5]:
'''
Define un array z de dim 8x8 completo de ceros
'''
z= np.zeros((8,8),dtype=np.int16)
print(z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [6]:
'''
Define el array 'ones' completo de unos de n dim
'''
ones = np.ones((3,2,2), dtype=np.int16)
print(ones)


[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [10]:
'''
Define un array como el que se muestra a continuación:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
'''

m = np.ones((8,8))
m[0,:]=m[-1,:]=m[:,0]=m[:,-1]=0

print(m)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
'''
Define un array con un range de 0 a 10 de dim 2
'''
r = np.array([range(10)])
print(r, "es de dimensión", r.ndim)


[[0 1 2 3 4 5 6 7 8 9]] es de dimensión 2


In [51]:
'''
Define un array 'h' con un range de 0 a 100 con un paso de 5 y una dim difrente de 1
'''



"\nDefine un array 'h' con un range de 0 a 100 con un paso de 5 y una dim difrente de 1\n"

In [52]:
'''.reshape sirve para darle una nueva forma a una matriz (de 3,2 a 1,6 o lo que sea) '''

'.reshape sirve para darle una nueva forma a una matriz (de 3,2 a 1,6 o lo que sea) '

In [ ]:
# Ejemplo practico de reshape
z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(z, z.shape)

# reshape a 2 dimensiones
print(z.reshape(4,5))

# reshape a 3 dimensiones
print(z.reshape(2,5,2))



## Leer y guardar ficheros

In [ ]:
# Crear una matriz
b = np.random.randint(0,100,size=(8,9), dtype=np.int32)

In [ ]:
# Guarda el array b en un csv. 
# - mediante %d le indicamos el formato
# - delimiter define el signo que se usará como delimitador. 

np.savetxt('file_data.csv', b, delimiter=';', fmt='%d')

In [ ]:
# Carga el contenido del csv en un array llamado file_data
file_data = np.loadtxt('file_data.csv', delimiter=';', dtype=np.int32)
print(file_data)