### Python numpy

tip para JN: #esc b / esc a para añadir celdas

In [3]:
'''
Lo primero es comprobar que tenemos instalado nmumpy y que lo podemos importar correctamente.
La ejecución de este bloque de código nos debe mostrar el array [1,2,3,4,5]
'''
import numpy as np

# Definición de un nuevo 'ndarray', de ahora en adelante lo llamaremos simplemente 'array'
test = np.array([1, 2, 3, 4, 5])
print(test)

[1 2 3 4 5]


### Primeros pasos

- a = np.array() -> para crear un array. 
- a.ndim -> para saber cuántas dimensiones tiene. 
- a.shape -> para saber la longitud de cada dimensión. **texto en negrita**

In [4]:
''' 
llamamos a np.array() para iniciar un array en numpy
'''

a = np.array([1,2,3,4,5])
print("de una dimensión:\n", a, "\n")

# de dos
b =[[1,2,3],[4,5,6]]
print("de dos dimensiones:\n", b, "\n")

# o más
c = np.array([
    [
        [1,2,3],[4,5,6]
    ],
    [
        [1,2,3],[4,5,6]
    ]   
    ])
print("o más:\n", c, "\n")

de una dimensión:
 [1 2 3 4 5] 

de dos dimensiones:
 [[1, 2, 3], [4, 5, 6]] 

o más:
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] 



In [17]:
'''
podemos usar dtype para ajustar el tipo de datos almacenandos y optimizar memoria. 
'''
print("por defecto, una matriz guarda datos de tipo", a.dtype)
a32 = np.array(a*10000, dtype = np.int32)
print("podemos definir a32:", a32, "con datos de tipo", a32.dtype, "\n")

'''
podemos redefinir el tipo de dato de una matriz con astype. 
astype no modifica la función original (hay que guardarlo en otra variable). 
Pero ojo, si metemos algo que se salga en memoria va a dar error (ej: un número muy grande).
Ej: como máximo int16 
'''
#a16 = a32.astype(np.int16)
a16 = np.array([1,2,32770], dtype=np.int16) 

print(a16, "parece que se ha roto")

por defecto, una matriz guarda datos de tipo int64
podemos definir a32: [10000 20000 30000 40000 50000] con datos de tipo int32 

[     1      2 -32766] parece que se ha roto


In [14]:
'''
Para obtener la información de una matriz, usamos: 
- ndim para obtener las dimensiones de un array
- shape para obtener su tamaño (shape devuelve una tupla).
- size para saber cuántos datos almacena. 
- itemsize para saber cuánto ocupa en memoria cada dato. 

'''
print("la matriz tiene", c.ndim, "dimensiones")
print("cada dimensión mide", c.shape)
print("guarda", c.size, "datos")
print("ocupa", c.itemsize, "bytes por dato")
print("en total: ", c.itemsize*c.size, "bytes")

la matriz tiene 3 dimensiones
cada dimensión mide (2, 2, 3)
guarda 12 datos
ocupa 8 bytes por dato
en total:  96 bytes


In [187]:
print("elementos de a16:", a16.size)
print("tamaño de cada elemento:", a16.itemsize)
print ("tamaño total:", a16.itemsize * a16.size)

elementos de a16: 5
tamaño de cada elemento: 2
tamaño total: 10


Ejercicios

In [188]:
'''
Define el array 'a' del 1 al 10. 
'''
a = np.array(range(1,11)) 
print(a)

'''
Es equivalente a np.arange(10). La función admite los mismos argumentos que range
'''

b = np.arange(10,0,-1)
print(b)

'''
Imprime la dimension del array y el shape
'''
print(a.ndim)
print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]
1
(10,)


In [189]:
''' 
Define de un array 'b' de dimensiones 2x3 a partir de listas anidadas
'''

b = np.array([
    [1,2,3,4,5],
    [4,5,6,7,8]
    ]
)


In [190]:
'''
Define un array 'c'  de dim 2x2x3 a partir de una lista de listas anidadas 
'''

c = np.array([
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]]
    ])
'''
Imprime el número total de elementos del array y el shape
'''
print(c.size)
print(c.shape)

12
(2, 2, 3)


## Accediendo y Modificando elementos de un array

In [51]:
# Array de 2x3
print(b)

[[1 2 3 4 5]
 [4 5 6 7 8]]


Obtener un elemento de un array

In [52]:
# Obtener un elemento concreto de un array [r,c] row column
b[1,4]

8

Obtener una fila completa de un array

In [56]:
# Para obtener una fila completa utilizamos la notación ':' como en la listas
b[0,:]

array([1, 2, 3, 4, 5])

Obtener una columna completa de un array

In [67]:
# define un array 'f' de dimensiones 4x5
f= np.array([
    [0,2,3,4,5],
    [1,5,6,7,8],
    [2,2,3,4,5],
    [3,5,6,7,8],
    ])
# Obtener la columna 3 de array f
f[:,2]

array([3, 6, 3, 6])

Otras formas de acceder a los elementos de un array

In [76]:
# Para acceder de una forma un poco más avanzada se utiliza [inicio: final: paso]
f[1, 4:1:-1]

# acceder a las filas pares: 
f[::2, :]

#darle la vuelta a las filas
f_inverted=f[::-1,]
print(f_inverted)

[[3 5 6 7 8]
 [2 2 3 4 5]
 [1 5 6 7 8]
 [0 2 3 4 5]]


Actualizar un elemento de un array

In [179]:
# Podemos actualizar la información de un array igual que seleccionando un elemento e igulandolo con un nuevo valor

Ejercicios

In [89]:
'''
Define un array 's' de tamaño 10 y selecciona el valor de la posición 5
'''
i = np.array([[range(5), range(5,10)], [range(55,60), range(105,110)]])
print(i)

[[[  0   1   2   3   4]
  [  5   6   7   8   9]]

 [[ 55  56  57  58  59]
  [105 106 107 108 109]]]


In [91]:
# cambiar los elementos de la primera fila de la segunda matriz, a 0
i[1,0,:]=0
print(i)

#cambiar la última columna de todo a 0
i[:,:,-1]=0
print(i)


[[[  0   1   2   3   4]
  [  5   6   7   8   9]]

 [[  0   0   0   0   0]
  [105 106 107 108 109]]]
[[[  0   1   2   3   0]
  [  5   6   7   8   0]]

 [[  0   0   0   0   0]
  [105 106 107 108   0]]]


In [ ]:
'''
Sobre el array s, selecciona el valor 5
'''

In [ ]:
'''
Define el array 's' de tamaño 25 y selecciona los valores pares
'''

In [ ]:
'''
Define el array 's' de tamaño 25 y selecciona los valores impares
'''

In [ ]:
'''
Sobre el array s, selecciona el uĺltimo valor
'''

In [ ]:
"""
Define el array 's' de tamaño 20 e invierte el orden de los valores
"""

In [ ]:
'''
Define un array s2 multidimensional de tamaño 2x2 y selecciona el valor de la segunda fila y la segunda columna
'''

In [ ]:
'''
Define el array:
[
[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
]
y selecciona el valor de la segunda dimension, primera fila, segunda columna
'''

In [ ]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a 99
'''

In [ ]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a (0,1), (2,3), (4,5), (6,7)
'''


## Inicializando diferentes tipos de arrays

#### Matriz de ceros

In [158]:
# Definir una matriz 
# primer arg -> tamaño (se introduce el shape con una tupla) con ceros. 
# argumento optional -> se puede indicar el tipo de dato con dtype
# np.zeros_like(matriz) -> toma la forma y el tipo de dato de otra matriz
print("matriz np.zeros(shape, dtype)\n", np.zeros((2,3,5), dtype=np.int32), "\n")
print("matriz np.zeros(b.shape)\n", np.zeros(b.shape), "\n")
print("matriz np.zeros_like(b)\n", np.zeros_like(b), "\n")

matriz np.zeros(shape, dtype)
 [[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]] 

matriz np.zeros(b.shape)
 [0. 0. 0. 0.] 

matriz np.zeros_like(b)
 [0 0 0 0] 



Matriz de unos

In [159]:
'''
misma cosa, pero se usa np.ones como función
'''


'\nmisma cosa, pero se usa np.ones como función\n'

Matriz de valores concretos

In [160]:
'''
usamos np.full(shape, value). 
También acepta como argumento dtype
Podemos usar un valor acabado en . para que np sepa que queremos un float. 
'''
p = np.full((5,3), 50.)
print(p)

[[50. 50. 50.]
 [50. 50. 50.]
 [50. 50. 50.]
 [50. 50. 50.]
 [50. 50. 50.]]


Matriz de valores concretos (full like)

In [161]:
'''
también podemos usar como referencia de shape y dtype otra matriz
'''
q = np.full_like(p, 75)
print(q)

[[75. 75. 75.]
 [75. 75. 75.]
 [75. 75. 75.]
 [75. 75. 75.]
 [75. 75. 75.]]


Matriz de números aleatorios

In [162]:
'''
usaremos np.random.rand 
OJO -> en este caso no se pasa el shape dentro de una tupla, sino que es un array de dos dimensiones y su tamaño se pasa en dos parámetros
'''
np.random.rand(5,2)
np.random.rand(2,5,2)*100

array([[[19.64662   ,  6.67965532],
        [14.6287479 , 49.68661531],
        [30.24435232, 55.58596953],
        [33.80328777, 76.89711982],
        [81.80593268, 59.07547559]],

       [[21.1302036 , 80.46904247],
        [49.87633485, 12.93277428],
        [88.106066  , 82.13965865],
        [84.81552179, 61.20081401],
        [ 3.91328594, 27.55098454]]])

In [163]:
'''
la función random randint sí admite luego un shape
'''
np.random.randint(0,100, (3,4))

array([[66, 72, 13, 68],
       [57, 28, 50, 84],
       [71, 53, 79, 23]])

Matriz identidad

In [164]:
# np.eye(5) o bien np.identity(5)
print(np.eye(5, dtype=np.int16))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


Ejercicios

In [165]:
'''
Define el array z de dim 1 completo de ceros
'''


'\nDefine el array z de dim 1 completo de ceros\n'

In [166]:
'''
Define un array z de dim 8x8 completo de ceros
'''


'\nDefine un array z de dim 8x8 completo de ceros\n'

In [167]:
'''
Define el array 'z' completo de ceros de n dim
'''


"\nDefine el array 'z' completo de ceros de n dim\n"

In [168]:
'''
Define el array 'd' completo de unos de n dim
'''


"\nDefine el array 'd' completo de unos de n dim\n"

In [169]:
'''
Define un array como el que se muestra a continuación:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
'''

'\nDefine un array como el que se muestra a continuación:\n[[0. 0. 0. 0. 0. 0. 0. 0.]\n [0. 1. 1. 1. 1. 1. 1. 0.]\n [0. 1. 1. 1. 1. 1. 1. 0.]\n [0. 1. 1. 1. 1. 1. 1. 0.]\n [0. 1. 1. 1. 1. 1. 1. 0.]\n [0. 1. 1. 1. 1. 1. 1. 0.]\n [0. 1. 1. 1. 1. 1. 1. 0.]\n [0. 0. 0. 0. 0. 0. 0. 0.]]\n'

In [170]:
'''
Define un array 'g' conun range de 0 a 10 de dim 2
'''


"\nDefine un array 'g' conun range de 0 a 10 de dim 2\n"

In [171]:
'''
Define un array 'h' con un range de 0 a 100 con un paso de 5 y una dim difrente de 1
'''


"\nDefine un array 'h' con un range de 0 a 100 con un paso de 5 y una dim difrente de 1\n"

In [ ]:
'''.reshape sirve para darle una nueva forma a una matriz (de 3,2 a 1,6 o lo que sea) '''

# Operaciones con arrays

## Operaciones básicas
las operaciones son "element wise". Se aplican a cada elemento de la matriz 

In [141]:
a = np.array([1, 2, 3, 4, 5])

In [142]:
#podemos sumar un número a todos los elementos
a+2

array([3, 4, 5, 6, 7])

In [152]:
# o sumar dos arrays SIEMPRE QUE SEAN DEL MISMO TAMAÑO
b=np.arange(5)*10
print(a+b)

[ 1 12 23 34 45]


In [145]:
# multiplicar o dividir
a*2
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
#elevar a un exponente (el exponente acepta floats, pero no números negativos)

In [147]:
a**(1/2)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

Ejercicios

In [157]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 1s. A contunuación suma los valores de ambos arrays y comprueba que los valores son correctos.
'''
a = np.random.randint(0,100, (4))
b = np.ones((4), dtype=np.int16)

print(a, b, a+b)


[57 64 88 46] [1 1 1 1] [58 65 89 47]


In [136]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 1s. A contunuación resta los valores de ambos arrays y comprueba que los valores son correctos.
'''

"\nDefine un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 1s. A contunuación resta los valores de ambos arrays y comprueba que los valores son correctos.\n"

In [137]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 2s. A contunuación multiplica o divide los valores de ambos arrays y comprueba que los valores son correctos.
'''

"\nDefine un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 2s. A contunuación multiplica o divide los valores de ambos arrays y comprueba que los valores son correctos.\n"

### Álgebra lineal

numpy py permite realizar operaciones matriciales como por elemplo:
- determinante:   np.linalg.det()
- inversa:        np.linalg.inv()
- producto        matricial: np.dot() o np.matmul() o a@b
- diagonal:       np.diag()
- inversa de una matriz: np.linalg.inv()



In [173]:
'''
se puede definir una matriz identidad
'''
identidad = np.eye(5)
print(np.linalg.det(identidad))


1.0


In [175]:
#para escribir una multiplicación matricial, podemos usar np.dot(a,b) o el signo arroba, que invoca a matmul: a@b
identidad @ identidad

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Más tipos de operaciones con arrays:
- **np.sum():** Suma de todos los elementos de un array
- **np.mean():** Media de todos los elementos de un array
- **np.std():** Desviación estándar de todos los elementos de un array
- **np.var():** Varianza de todos los elementos de un array
- **np.min():** Valor mínimo de todos los elementos de un array
- **np.max():** Valor máximo de todos los elementos de un array
- **np.argmin():** Indice del valor mínimo de un array
- **np.argmax():** Indice del valor máximo de un array
- **np.cumsum():** Sumatoria acumulada de un array
- **np.cumprod():** Producto acumulado de un array
- **np.flip():** Inversa de un array


In [137]:
#obtener valor máximo de cada fila


Ejercicios

In [138]:
import numpy as np

In [139]:
'''
Calcula la mediana de un array
'''

'\nCalcula la mediana de un array\n'

In [178]:
'''
calcula la media de una matriz
'''
print(c)
print(np.max(c))
print("máximo de cada columna", np.max(c, axis=0)) 
print("máximo de cada fila", np.max(c, axis=1)) 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
6
máximo de cada columna [[1 2 3]
 [4 5 6]]
máximo de cada fila [[4 5 6]
 [4 5 6]]
